### ISSUE TITLE
Send ODM output to log file

### ISSUE THREAD

**Issue by samsoe** [samsoe/mpg_aerial_survey#10]

**Comment by samsoe** [comment]
Also consider tmux for realtime monitoring

**Comment by mosscoder** [comment]
Startup process output (and all processes) are accessible[ via Logs Explorer](https://console.cloud.google.com/logs/query;query=resource.type%3D%22gce_instance%22%0Aresource.labels.instance_id%3D%226309833244775831746%22;timeRange=2023-06-07T18:54:18.842Z%2F2023-06-08T15:54:18.842281Z;cursorTimestamp=2023-06-08T04:07:49.396564Z?project=mpg-aerial-survey-375719): 

It appears you can download logs for a specific time range.

**Comment by mosscoder** [comment]
<img width="1668" alt="Screenshot 2023-06-08 at 8 58 08 AM" src="https://github.com/samsoe/mpg_aerial_survey/assets/17579844/f1e9251e-1535-4500-b2e7-b6b03e515eb6">
