### ISSUE TITLE
Ensure docker is running before post_process.py

### ISSUE THREAD

**Issue by mosscoder** [samsoe/mpg_aerial_survey#8]
I've noticed that I must manually start the docker daemon before I can issue commands to ODM in a local OSX environment. Do we need to start the docker daemon on the linux VMs, or is it running by default as suggested here?

https://docs.docker.com/config/daemon/start/

**Comment by samsoe** [comment]
I have not needed to start the docker daemon for each new VM instance. I setup docker when I setup the first template machine. It has been configured and running for each new 'create instance'
